# Generated by Django 5.0 on 2024-01-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_doctordetail_delete_doctorinfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
