# Generated by Django 5.0 on 2024-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_doctordetail_image_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='DoB',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
