# Generated by Django 5.0 on 2024-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctor_dob_doctor_email_doctor_phone_doctor_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER')], default=2, unique=True),
        ),
    ]
