# Generated by Django 5.0 on 2024-01-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DoB',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
