# Generated by Django 5.0 on 2024-01-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=None),
        ),
    ]
