# Generated by Django 5.0 on 2024-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_doctordetail_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
