# Generated by Django 5.0 on 2024-01-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
