# Generated by Django 5.0 on 2024-01-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalinfor',
            name='dental_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dental_branch_info', to='dental.dentalbraches'),
        ),
    ]
