# Generated by Django 5.0 on 2024-01-07 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_doctordetail_delete_doctorinfor'),
        ('dental', '0003_alter_dentalbraches_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalbraches',
            name='user',
        ),
        migrations.AddField(
            model_name='dentalbraches',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dental_branch_doctor', to='core.doctor'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('brach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brach_room', to='dental.dentalbraches')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
