# Generated by Django 5.0 on 2024-01-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0005_alter_room_brach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='brach',
            new_name='branch',
        ),
    ]
