# Generated by Django 5.0 on 2024-01-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_date'),
        ('core', '0005_doctor_doctordetail_delete_doctorinfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_booking', to='core.doctor'),
        ),
    ]
