# Generated by Django 5.0 on 2024-01-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_room_alter_booking_status_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='type',
        ),
    ]
