# Generated by Django 5.0 on 2024-01-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_item', to='app.menuitem'),
        ),
    ]
