# Generated by Django 5.0 on 2024-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_booking_booking_name_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
