# Generated by Django 5.0 on 2024-01-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_booking_total_money_alter_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doctor',
        ),
    ]
