# Generated by Django 5.0 on 2024-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_booking_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='incurred',
            field=models.IntegerField(default=0),
        ),
    ]
