# Generated by Django 5.0 on 2024-01-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_incurred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='incurred',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
